backend:
#  name: test-repo
#  name: git-gateway
#  branch: master
  name: github
  repo: orkisz/przedszkole-site

locale: pl

media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  config:
    cloud_name: dswesmbkz
    api_key: 145566431588812
    multiple: true

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - label: 'Tytuł'
        name: 'title'
        widget: 'string'
      - label: 'Data publikacji'
        name: 'date'
        widget: 'datetime'
      - label: 'Treść'
        name: 'body'
        widget: 'markdown'
      - label: 'Obraz'
        name: 'images'
        widget: 'image'
        required: false
        allow_multiple: true
        media_library:
          config:
            multiple: true

  - name: 'group'
    label: 'Grupa'
    folder: 'content/group'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{order}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Nazwa grupy', name: 'name', widget: 'string' }
      - { label: 'Opis', name: 'description', widget: 'string' }
      - { label: 'Obrazek', name: 'image', widget: 'image', required: true }
      - { label: 'Nr porządkowy', name: 'order',  widget: 'number', value_type: 'int', min: 1, max: 3, required: true }
